#!/usr/bin/with-contenv bash

# Trick GYB into storing data in the docker volume. Make sure it ends in '/'
export STATICX_PROG_PATH=/config/

# Parse env variables into GYB command
if [ -n "${MEM_LIMIT}" ]; then
  MEM_LIMIT=" --memory-limit ${MEM_LIMIT}"
fi

if [ -n "${EMAIL}" ]; then
  EMAIL=" --email ${EMAIL}"
fi

if [ -n "${DEBUG}" ]; then
  DEBUG=" --debug"
fi

LOCAL_FOLDER=" --local-folder ${DEST:-/config/data}"

CMD="$@${MEM_LIMIT}${EMAIL}${LOCAL_FOLDER}${DEBUG}"
echo "[Running] python3 /app/src/gyb.py ${CMD}"

# Make sure jobs aren't competing with each other. Placing here so we output what
# command we were trying to run
exec 100< "$(realpath $0)"
flock -n 100 || { \
  echo "ERROR: /app/gyb is already running in another (long running?) process" \
  && exit 1; \
}

# Away we go...
python3 /app/src/gyb.py \
  ${CMD}