#!/usr/bin/with-contenv bash

exec 3>&1
set -o pipefail

OUT=$(exec "$@" 2>&1 | tee >(cat - >&3))

if [ $? -ne 0 ]; then
	sendmail -t <<-EOF 
	From: ${MAIL_FROM}
	To: ${MAIL_TO}
	Subject: ${MAIL_SUBJECT:-Error running Got Your Back job}

	${OUT}
	EOF
fi